<Project>
  <PropertyGroup>
    <VersionMajor>0</VersionMajor>
    <VersionMinor>8</VersionMinor>
    <VersionBase>$(VersionMajor).$(VersionMinor)</VersionBase>
    <Authors>Soroush Falahati, LenovoLegionToolkit-Team</Authors>
    <Copyright>Copyright © 2026</Copyright>
    <RepositoryUrl>https://github.com/LenovoLegionToolkit-Team/NvAPIWrapper</RepositoryUrl>
    <PackageProjectUrl>https://github.com/LenovoLegionToolkit-Team/NvAPIWrapper</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
</Project>
